import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import Link from 'next/link'
import { Menu } from 'lucide-react';

import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet"

const App = () => {
  return (
    <Menu />
  );
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className ="nav-section bg-white border border-blue-600 col-span-12 row-span-2">
        <h2 className="menu flex  flex-wrap  justify-between ">
          <div className="flex justify-start items-center m-3">
            <img src="/dollarlogo.jpg " alt="Photo"  height = {70} width={70}  />
            <a className="  first-line:text-3xl font-bol mx-3 p-3 font-bold items-centre"> Market Geek <br/> Scan, invest and repeat...</a>
          </div>

          <div className="md:flex hidden justify-end  text-white text-xl bg-blue-300 rounded-full items-center py-0.5 px-1 gap-10 mx-5 my-3 font-bold ">
          <Link href={"/"}>
            <button className="border-spacing-3 p-1 rounded-full bg-blue-800"> Home </button>
          </Link>           

          <Link href={"/Charts"}>
            <button className="border-spacing-3 p-1 rounded-full bg-blue-800"> Charts</button>
            </Link>

            <Link href={"/About"}> 
           <button className="border-spacing-3 p-1 rounded-full bg-blue-800">About</button>
           </Link>
          
          </div>


          <div className='flex md:hidden'>

              <Sheet>
              <SheetTrigger> <Menu /> </SheetTrigger>
              <SheetContent>
              <SheetHeader>
              <ul className='text-lg font-medium gap-x-4'>
                              <li>
                                <Link href={"/"}>Home </Link>
                              </li>
                              <li>
                                <Link href={"/About"}>About</Link>
                              </li>
                              <li>
                                <Link href={"/Charts"}>Charts</Link>
                              </li>
                              
                            </ul>

              </SheetHeader>
              </SheetContent>
              </Sheet>
            </div>



          </h2>
      </nav>

  

        {children}
        
        <footer className ="bg-zinc col-span-12 row-span-2">
        <div className="flex justify-center">
        <div className="flex flex-col items-center">
          <h3 className="font-bold mb-2">Contact Details</h3>
            <p>Phone: <a href="tel:YOUR_PHONE_NUMBER">+92-301-8210011</a></p>
            <p>Email: <a href="mailto:YOUR_EMAIL">abdulmoeedkhan999@gmail.com</a></p>
            <p>LinkedIn: <a href="YOUR_LINKEDIN_PROFILE_URL">www.linkedin.com/in/moeedkhan</a></p>
        </div>
</div>

      </footer></body>
    </html>
  )
}
